### ISSUE TITLE
maven-project

### ISSUE THREAD

**Issue by khmarbaise** [mebigfatguy/fbp-maven-plugin#3]
You should use maven-project 3.0 at minimum or would like to be compatible with Maven2  ?

**Comment by mebigfatguy** [comment]
so 3.0-alpha-2 is the latest? ok.. was bitten by copying tutorials...

thanks!

**Comment by khmarbaise** [comment]
Ah sorry you should replace it with maven-core instead...and do not us 3.0-alpha-2 cause some components have moved to a different artifact...
