### ISSUE TITLE
Injected reactorProjects

### ISSUE THREAD

**Issue by khmarbaise** [mebigfatguy/fbp-maven-plugin#4]
Currently you let inject the `reactorProjects`. This is only for Maven 2 working correctly cause if you do on maven a thing like this. `mvn -pl AAA ...` this will not work anymore.

There is an option via:

```java
 getMavenSession().getProjectDependencyGraph().getSortedProjects()
```
will get you the list of projects...also under Maven 3...

**Comment by mebigfatguy** [comment]
hmm seems to be the same results. no dependencies.

**Comment by mebigfatguy** [comment]
ah! the plugin is called recursively for each project. And the last project had no dependencies so it wiped everything out. just had to set a flag that said, this was called already --ignore.

works!

thanks for all the help.
